#ifndef __SPI_TEST_H__
#define __SPI_TEST_H__

typedef enum
{
	SPI_TEST_SCENARIO_NONE,
	SPI_TEST_SCENARIO_PHYSICAL,
	SPI_TEST_SCENARIO_MASTER_SENDING,
	SPI_TEST_SCENARIO_SLAVE_SENDING,
	SPI_TEST_SCENARIO_COMPLEX_SENDING,
}SPI_TEST_SCENARIO_T;

typedef enum
{
	SPI_TEST_MRDY_IRQ,
	SPI_TEST_SRDY_IRQ,
	SPI_TEST_SUBMRDY_IRQ,
	SPI_TEST_SUBSRDY_IRQ
}SPI_TEST_INFO_T;


extern SPI_TEST_SCENARIO_T spi_test_scenario_mode;
extern void spi_test_run (SPI_TEST_SCENARIO_T scenario, int param);
#endif
